CREATE TABLE `sap_production_order_operation_data`
(
    `ManufacturingOrder`            varchar(12) NOT NULL,
    `ManufacturingOrderSequence`    varchar(6) NOT NULL,
    `OrderInternalBillOfOperations` varchar(8) NOT NULL,
    `OrderIntBillOfOperationsItem`  varchar(4) NOT NULL,
    `MfgOrderSequenceText`          varchar(40) DEFAULT NULL,
    `ManufacturingOrderOperation`   varchar(4) DEFAULT NULL,
    `ManufacturingOrderSubOperation` varchar(4) DEFAULT NULL,
    `ManufacturingOrderCategory`    varchar(2) DEFAULT NULL,
    `ManufacturingOrderType`        varchar(4) DEFAULT NULL,
    `MfgOrderOperationText`         varchar(40) DEFAULT NULL,
    `OperationIsCreated`            varchar(1) DEFAULT NULL,
    `OperationIsReleased`           varchar(1) DEFAULT NULL,
    `OperationIsPrinted`            varchar(1) DEFAULT NULL,
    `OperationIsConfirmed`          varchar(1) DEFAULT NULL,
    `OperationIsPartiallyConfirmed` varchar(1) DEFAULT NULL,
    `OperationIsDeleted`            varchar(1) DEFAULT NULL,
    `OperationIsTechlyCompleted`    varchar(1) DEFAULT NULL,
    `OperationIsClosed`             varchar(1) DEFAULT NULL,
    `OperationIsScheduled`          varchar(1) DEFAULT NULL,
    `OperationIsPartiallyDelivered` varchar(1) DEFAULT NULL,
    `OperationIsDelivered`          varchar(1) DEFAULT NULL,
    `ProductionPlant`               varchar(4) DEFAULT NULL,
    `WorkCenterInternalID`          varchar(8) DEFAULT NULL,
    `WorkCenterTypeCode`            varchar(1) DEFAULT NULL,
    `WorkCenter`                    varchar(8) DEFAULT NULL,
    `OperationControlProfile`       varchar(4) DEFAULT NULL,
    `OpErlstSchedldExecStrtDte`     varchar(80) DEFAULT NULL,
    `OpErlstSchedldExecStrtTme`     varchar(80) DEFAULT NULL,
    `OpErlstSchedldExecEndDte`      varchar(80) DEFAULT NULL,
    `OpErlstSchedldExecEndTme`      varchar(80) DEFAULT NULL,
    `OpActualExecutionStartDate`    varchar(80) DEFAULT NULL,
    `OpActualExecutionStartTime`    varchar(80) DEFAULT NULL,
    `OpActualExecutionEndDate`      varchar(80) DEFAULT NULL,
    `OpActualExecutionEndTime`      varchar(80) DEFAULT NULL,
    `ErlstSchedldExecDurnInWorkdays` int(32) DEFAULT NULL,
    `OpActualExecutionDays`         int(32) DEFAULT NULL,
    `OperationUnit`                 varchar(3) DEFAULT NULL,
    `OpPlannedTotalQuantity`        varchar(13) DEFAULT NULL,
    `OpTotalConfirmedYieldQty`      varchar(13) DEFAULT NULL,
    `LastChangeDateTime`            varchar(80) DEFAULT NULL,
    PRIMARY KEY (`ManufacturingOrder`, `ManufacturingOrderSequence`, `OrderInternalBillOfOperations`, `OrderIntBillOfOperationsItem`),
    CONSTRAINT `SAPProductionOrderOperationData_fk` FOREIGN KEY (`ManufacturingOrder`) REFERENCES `sap_production_order_general_data` (`ManufacturingOrder`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
